version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    command: node index.js
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    command: node server.js
